const state={mode:'map',dataset:null,map:null,markers:[],deferredPrompt:null};
const $=id=>document.getElementById(id);
const years=['2015','2020','2025'];
const monthNames=['Intero anno','Gennaio','Febbraio','Marzo','Aprile','Maggio','Giugno','Luglio','Agosto','Settembre','Ottobre','Novembre','Dicembre'];

function fillYears(){for(const id of ['yearSelect','compareYearA','compareYearB']){$(id).innerHTML=years.map(y=>`<option value="${y}">${y}</option>`).join('')} $('yearSelect').value='2025';$('compareYearA').value='2015';$('compareYearB').value='2025'}
function colorFor(v){if(v<15)return'#35d07f';if(v<20)return'#e6cf43';if(v<25)return'#ff914d';return'#ff5864'}
function avg(rows){return rows.reduce((s,r)=>s+r.value,0)/Math.max(rows.length,1)}
function rowsForYear(y){return state.dataset?.years?.[y]||[]}
function clearMarkers(){state.markers.forEach(m=>m.remove());state.markers=[]}
function markerElement(row,label){const el=document.createElement('button');el.className='aq-marker';el.style.cssText=`width:34px;height:34px;border-radius:50%;border:3px solid rgba(255,255,255,.9);background:${colorFor(row.value)};color:#06101b;font-weight:900;font-size:10px;box-shadow:0 2px 10px rgba(0,0,0,.45);cursor:pointer`;el.textContent=label??Math.round(row.value);el.setAttribute('aria-label',`${row.name}: ${row.value}`);return el}
function renderMarkers(rows){clearMarkers();rows.forEach(row=>{const marker=new maplibregl.Marker({element:markerElement(row)}).setLngLat([row.lon,row.lat]).setPopup(new maplibregl.Popup({offset:20}).setHTML(`<strong>${row.name}</strong><br>${row.value} µg/m³`)).addTo(state.map);state.markers.push(marker)})}
function renderDifference(){const a=rowsForYear($('compareYearA').value),b=rowsForYear($('compareYearB').value);const index=new Map(a.map(r=>[r.id,r]));const rows=b.filter(r=>index.has(r.id)).map(r=>({...r,value:+(r.value-index.get(r.id).value).toFixed(1)}));clearMarkers();rows.forEach(row=>{const el=markerElement({...row,value:Math.abs(row.value)},`${row.value>0?'+':''}${row.value}`);el.style.background=row.value<=0?'#35d07f':'#ff5864';const marker=new maplibregl.Marker({element:el}).setLngLat([row.lon,row.lat]).setPopup(new maplibregl.Popup({offset:20}).setHTML(`<strong>${row.name}</strong><br>Δ ${row.value>0?'+':''}${row.value} µg/m³`)).addTo(state.map);state.markers.push(marker)});return rows}
function renderStationList(rows,isDiff=false){$('stations').innerHTML=rows.map(r=>`<div class="station-row"><i style="background:${isDiff?(r.value<=0?'#35d07f':'#ff5864'):colorFor(r.value)}"></i><div><strong>${r.name}</strong><small>${r.id}</small></div><b>${isDiff&&r.value>0?'+':''}${r.value.toFixed(1)}</b></div>`).join('')}
function render(){if(!state.dataset||!state.map)return;const year=$('yearSelect').value;const month=+$('monthSelect').value;const source=$('sourceSelect').value;const sourceName=$('sourceSelect').selectedOptions[0].textContent;let rows=rowsForYear(year);$('comparePanel').classList.toggle('hidden',state.mode==='map');if(source!=='demo'){$('dataNotice').textContent='Connettore dati non ancora attivo · fallback demo'}else{$('dataNotice').textContent='Dati dimostrativi'}
if(state.mode==='difference'){rows=renderDifference();renderStationList(rows,true);$('mapBadge').textContent=`Δ ${$('compareYearB').value} − ${$('compareYearA').value}`;$('avgValue').textContent=(avg(rows)>=0?'+':'')+avg(rows).toFixed(1)}else if(state.mode==='compare'){const b=rowsForYear($('compareYearB').value);rows=b;renderMarkers(rows);renderStationList(rows);$('mapBadge').textContent=`${$('compareYearA').value} ↔ ${$('compareYearB').value}`;$('avgValue').textContent=avg(b).toFixed(1)}else{renderMarkers(rows);renderStationList(rows);$('mapBadge').textContent=`${$('pollutantSelect').value} · ${year}`;$('avgValue').textContent=avg(rows).toFixed(1)}
$('stationCount').textContent=rows.length;$('periodValue').textContent=month?monthNames[month]:year;$('sourceValue').textContent=sourceName}
async function loadData(){const [data,appVersion,dataVersion]=await Promise.all([fetch('data/rome-demo.json').then(r=>r.json()),fetch('version.json').then(r=>r.json()),fetch('data/version.json').then(r=>r.json())]);state.dataset=data;$('appVersion').textContent=appVersion.version;$('dataVersion').textContent=dataVersion.version}
function initMap(){state.map=new maplibregl.Map({container:'map',style:'https://tiles.openfreemap.org/styles/liberty',center:[12.4964,41.9028],zoom:10.2,attributionControl:true});state.map.addControl(new maplibregl.NavigationControl({showCompass:false}),'top-right');state.map.on('load',render)}
function bind(){document.querySelectorAll('.tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(b=>b.classList.remove('active'));btn.classList.add('active');state.mode=btn.dataset.mode;render()}));['sourceSelect','pollutantSelect','yearSelect','monthSelect','compareYearA','compareYearB'].forEach(id=>$(id).addEventListener('change',render));window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.deferredPrompt=e;$('installBtn').classList.remove('hidden')});$('installBtn').addEventListener('click',async()=>{if(!state.deferredPrompt)return;state.deferredPrompt.prompt();await state.deferredPrompt.userChoice;state.deferredPrompt=null;$('installBtn').classList.add('hidden')})}
async function boot(){fillYears();bind();await loadData();initMap();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js')}
boot().catch(err=>{console.error(err);$('dataNotice').textContent='Errore di inizializzazione'})
